### ISSUE TITLE
error when following installation instructions

### ISSUE THREAD

**Issue by salemine** [o-oconnell/mp4grep#10]
```bash
$ source install.sh
readlink: invalid option -- 'b'
Try 'readlink --help' for more information.
$
```

**Comment by o-oconnell** [comment]
Can you provide steps to reproduce this issue?

**Comment by KoolenDasheppi** [comment]
I fixed it by adding two hyphens in a specific fashion to the first line of the install.sh script, as detailed in the solution to this StackOverflow post: [https://unix.stackexchange.com/questions/30446/strange-behavior-in-dirname-readlink-f-0](https://unix.stackexchange.com/questions/30446/strange-behavior-in-dirname-readlink-f-0)
