### ISSUE TITLE
Timestamp generation has a formatting bug

### ISSUE THREAD

**Issue by ciacon** [o-oconnell/mp4grep#14]
Timestamps look fine for the first hour. After the hour, things get a little weirder:
[...]
59:59
59:59
1:0000
1:0001
[...until...]
1:10:00
1:10:01

**Comment by o-oconnell** [comment]
This has been fixed in 0.1.1. Tags, readme, and help message should be updated soon as well. You will probably want to run mp4grep --clear-cache and re-transcribe your files to remove the incorrect timestamps.

**Comment by o-oconnell** [comment]
Everything should be working now, please let me know if you are still having any problems and I will reopen this issue.
