### ISSUE TITLE
mp4grep won't accept a directory

### ISSUE THREAD

**Issue by jroneilky** [o-oconnell/mp4grep#24]
Hello, great tool, I really like it. This is maybe user error, but I'm running into a problem when feeding it a directory:

```
$ ls test
test1.wav*  test2.wav*  test3.wav*

$ mp4grep "test" test/
test3.wav does not exist, not transcribing.
test2.wav does not exist, not transcribing.
test1.wav does not exist, not transcribing.
```

If I point it directly to one of the files, it works as expected, but pointing it to a directory doesn't seem to work.

I encounter the same behavior with the prebuilt binary as well as one I build myself. I'm using version 0.1.4 on Arch.

**Comment by o-oconnell** [comment]
Hey @jroneilky, the latest commit fixes this issue. I'll make a prebuilt binary and release for it soon.

**Comment by o-oconnell** [comment]
0.1.5 resolves this.
